name: $(Build.DefinitionName).1.0$(Rev:.r)

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool: Docker

resources:
  repositories:
    - repository: templates
      type: git
      name: CapitalOnTap/ADO-Deploy-Tools

stages :
  - stage: Build_Docker
    jobs:
    - deployment: docker_build_deploy
      continueOnError: false
      environment: ci_build
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: PowerShell@2
                displayName: Split_Build_Number
                continueOnError: false
                inputs:
                  targetType: inline
                  script: | 
                    $build = "$(Build.BuildNumber)"
                    $pos = $build.IndexOf(".")
                    $buildnumber = $build.Substring($pos+1)
                    echo "##vso[task.setvariable variable=buildnumber]$buildnumber"
              - task: Docker@2
                displayName: Login to ACR
                inputs:
                  command: login
                  containerRegistry: ACR Capitalontappg
              - task: Docker@2
                displayName: BuildPush
                inputs:
                  command: buildAndPush
                  Dockerfile: ./dockerfile
                  repository: kierantest
                  tags: $(buildnumber)
              - task: Docker@2
                displayName: Logout of ACR
                inputs:
                  command: logout
                  containerRegistry: ACR Capitalontappg

  - stage: App_Settings
    jobs:
    - job: App_settings
      variables:
        - group: System Variables
        - name: ProjectName
          value: kierantest 
      steps:
            - checkout: self
              clean: true
              submodules: true
            - task: PowerShell@2
              displayName: Split_Build_Number
              continueOnError: false
              inputs:
                targetType: inline
                script: | 
                  $build = "$(Build.BuildNumber)"
                  $pos = $build.IndexOf(".")
                  $buildnumber = $build.Substring($pos+1)
                  echo "##vso[task.setvariable variable=buildnumber]$buildnumber"
            - task: PowerShell@2
              displayName: Information
              continueOnError: false
              inputs:
                targetType: inline
                script: |
                  Write-host "Directory: $pwd"
                  Write-host "Build Number: $(Build.BuildNumber)"
                  echo "$(buildnumber)"
            - task: PowerShell@2
              displayName: Find_App_Settings
              continueOnError: false
              inputs:
                targetType: inline
                script: if ("appsettings.json" -in (Get-ChildItem).name) {Write-host "found appsettings file!"} else {write-error "Can't find the appsettings file..."}
            - task: replacetokens@3
              inputs:
                targetFiles: '**/deployment.yaml'
                encoding: 'auto'
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '${'
                tokenSuffix: '}'
                useLegacyPattern: false
                enableTransforms: false
                enableTelemetry: true
            - task: ArchiveFiles@2
              displayName: Zip_Files
              inputs:
                rootFolderOrFile: '$(System.DefaultWorkingDirectory)' 
                includeRootFolder: false 
                archiveType: 'zip' # Options: zip, 7z, tar, wim
                archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip' 
                replaceExistingArchive: true 
            - task: PowerShell@2
              displayName: Download_Octo_CLI
              continueOnError: false
              inputs:
                targetType: inline
                script: |
                  mkdir octo
                  Invoke-WebRequest https://download.octopusdeploy.com/octopus-tools/7.4.3459/OctopusTools.7.4.3459.win-x64.zip -OutFile .\octo\octo.zip
                  Expand-Archive -LiteralPath '.\octo\octo.zip' -DestinationPath .\octo\
            - task: PowerShell@2
              displayName: Push_Zip
              continueOnError: false
              inputs:
                targetType: inline
                script: .\octo\octo.exe push --package $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip --server https://octopus.capitalontap.com --apiKey $(octopus-api-key)
